export const ELEMENTS = {
    botao_login: '.shop-menu > .nav > :nth-child(4) > a',
    input_nome: '[data-qa="signup-name"]',
    input_email: '[data-qa="signup-email"]',
    botao_cadastrar: '[data-qa="signup-button"]',
    checkbox_genero: '#id_gender1',
    input_senha: '[data-qa="password"]',
    input_dia: '[data-qa="days"]',
    input_mes: '[data-qa="months"]',
    input_ano: '[data-qa="years"]',
    checkbox_newsletter: '#newsletter',
    checkbox_receber: '#optin',
    input_first_name: '[data-qa="first_name"]',
    input_last_name: '[data-qa="last_name"]',
    input_company: '[data-qa="company"]',
    input_address: '[data-qa="address"]',
    input_address2: '[data-qa="address2"]',
    input_pais: '[data-qa="country"]',
    input_estado: '[data-qa="state"]',
    input_cidade: '[data-qa="city"]',
    input_cep: '[data-qa="zipcode"]',
    input_cel: '[data-qa="mobile_number"]',
    botao_criar_conta: '[data-qa="create-account"]',
    msg_conta_criada: '[data-qa="account-created"]',
    botao_continuar: '[data-qa="continue-button"]',
    mensagem_erro: '.signup-form > form > p'

}